# Generated by Django 5.2.3 on 2025-07-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=50, unique=True, verbose_name='Bus Line Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Bus Line',
                'verbose_name_plural': 'Bus Lines',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mm', models.CharField(max_length=255, unique=True, verbose_name='Stop Name (Myanmar)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='Stop Name (English)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Bus Stop',
                'verbose_name_plural': 'Bus Stops',
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Stop Order')),
                ('distance_to_next_stop_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance to Next Stop (km)')),
                ('estimated_time_to_next_stop_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estimated Time to Next Stop (minutes)')),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='bus_routes.busline', verbose_name='Bus Line')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='bus_routes.busstop', verbose_name='Bus Stop')),
            ],
            options={
                'verbose_name': 'Route Segment',
                'verbose_name_plural': 'Route Segments',
                'ordering': ['bus_line', 'order'],
                'unique_together': {('bus_line', 'bus_stop', 'order')},
            },
        ),
    ]
