# Generated by Django 5.2.3 on 2025-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesegment',
            name='distance_to_next_stop_km',
        ),
        migrations.RemoveField(
            model_name='routesegment',
            name='estimated_time_to_next_stop_minutes',
        ),
        migrations.AddField(
            model_name='busstop',
            name='road_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Road Name (English)'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='road_name_mm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Road Name (Myanmar)'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Stop Name (English)'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name_mm',
            field=models.CharField(max_length=255, verbose_name='Stop Name (Myanmar)'),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('name_en', 'road_name_en'), ('name_mm', 'road_name_mm')},
        ),
    ]
