# Generated by Django 5.2.3 on 2025-08-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0004_routesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busline',
            name='line_number',
            field=models.IntegerField(max_length=50, unique=True, verbose_name='Bus Line Number'),
        ),
    ]
