# Generated by Django 5.2.3 on 2025-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0005_alter_busline_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busline',
            name='line_number',
            field=models.IntegerField(unique=True, verbose_name='Bus Line Number'),
        ),
    ]
