# Generated by Django 5.2.3 on 2025-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0008_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
